### ISSUE TITLE
[macOS] Startool not working on macOS

### ISSUE THREAD

**Issue by shinra-electric** [Wargus/stargus#62]
I'm trying to extract the Starcraft game data on Mac, but Startool is not working. 

First I pointed it to a PC install (Have a Wine install), where StarDat.mpq and BrooDat.mpq are present. Neither files are shown as detected. Then Startool will segfault. 

Then I tried again but this time with INSTALL.EXE present. It is detected, but then it will fail with a file not found error: 
`libc++abi: terminating due to uncaught exception of type FileNotFoundException: File not found: 'dataset/units.json'.`

Here is the terminal log: 
[Startool Output.txt](https://github.com/Wargus/stargus/files/13403191/Startool.Output.txt)

**Comment by shinra-electric** [comment]
Update: I noticed that the missing `dataset/units.json` file was in the Stargus source directory, so I copied all of the source files into the Stargus.app bundle and ran it again. 

It ran, but it did not seem to run completely. Even though I used the -v command, it didn't convert any videos. 
[Startool Output 2.txt](https://github.com/Wargus/stargus/files/13403240/Startool.Output.2.txt)

I launched Stargus using the command line, and it fails saying that there are missing items, including the ogg files. 
[Stargus Output.txt](https://github.com/Wargus/stargus/files/13403243/Stargus.Output.txt)

**Comment by shinra-electric** [comment]
Update 2: It turns out I was using the -v arg in the wrong place. 

using the command `./startool -v /source_dir /destination_dir` got it working. However, the music files were not converted, and Stargus will still crash saying that it is missing `music/title.ogg`. There was no music folder extracted...
[Startool Output 3.txt](https://github.com/Wargus/stargus/files/13403332/Startool.Output.3.txt)

**Comment by andreas-volz** [comment]
The sound parameter was documented wrong. You've to run startool with --sound or -s to extract the audio.
I pushed the help change to my feature branch. I'll merge it with the next feature change to the official repo.
But it the parameter works, it's just the wrong help.

**Comment by shinra-electric** [comment]
Thanks for the tip! Using `./startool -v -s  /source_dir /destination_dir` did extract the music and sound files! I can get a little bit further now. 

However, Stargus still won't launch at all when opening the app bundle, and crashes when trying to load the menu when run through terminal. There is no error printed in the terminal output (except for the few missing Lua files that are the same as in the previous output above). Here is the system crash report in case it might help at all... 

[Stargus crash report.txt](https://github.com/Wargus/stargus/files/13403433/Stargus.crash.report.txt)

**Comment by shinra-electric** [comment]
Here are the steps I took in getting this far, just for anyone else following along: 

1. Built Stratagus and Stargus (including running the bundle script)
2. Copied the install.exe from a starcraft CD to the root of the stargus folder
3. Copied startool from `stargus/build/src/` to the root of the stargus folder
4. Ran startool from the command line with `./startool -v -s  /source_dir /destination_dir` where source is the stargus folder and the destination directory is `~/Library/Application Support/Stratagus/data.Stargus`
5. Cd'd into the stargus.app bundle `cd Stargus.app/Contents/MacOS/`
6. Ran ./stargus
